### ISSUE TITLE
Tests broken?

### ISSUE THREAD

**Issue by thiagodemellobueno** [krambuhl/metalsmith-rewrite#1]
```
$ pwd
/Users/XXXX/repos/metalsmith-rewrite
$ npm test

> metalsmith-rewrite@0.1.2 test /Users/XXXX/repos/metalsmith-rewrite
> tape test/*.test.js

/Users/XXXX/repos/metalsmith-rewrite/node_modules/metalsmith/lib/index.js:190
Metalsmith.prototype.build = unyield(function*(){
                                             ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/XXXX/repos/metalsmith-rewrite/node_modules/metalsmith/index.js:6:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Test failed.  See above for more details.
$ 
```

**Comment by krambuhl** [comment]
Looks related to metalsmith 2.0 (https://github.com/segmentio/metalsmith/issues/87)  2.0+ uses generator function only available Node v0.11+  Using Metalsmith 1.7 with Node v0.10 should resolve this issue if your Node environment can't be updated.  

Closing issue for now, please reopen if you find tests to be broken once environment is happy.
